import 'package:get/get.dart';

class LocalStrings extends Translations {
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'login': 'Login',
          'createAccount': 'Create Account',
          'settings': 'Settings',
          'account': 'Account',
          'search': 'Search Products',
          'price': 'Price',
          'discount': 'Discount',
          'descriptions': 'Descriptions',
          'itemsFound': 'Items Found',
          'payment': 'Payment',
          'items': 'Items',
          'favorites': 'Favorites',
          'totalPrice': 'Total Price',
          'total': 'Total',
          'addToCart': 'Add to Cart',
          'buy': 'Buy',
          'pay': 'Pay',
          'checkout': 'Checkout',
          'cancel': 'Cancel',
          'change': 'Change',
          'continue': 'Continue',
          'addToWishList': 'Add to wishlist',
          'removeWishList': 'Remove from wishlist',
          'homePage': 'Home page',
          'cartPage': 'Cart page',
          'orderPage': 'Orders page',
          'cart': 'Cart',
          'setAddress': 'Set Address',
          'orderSuccess': 'Successfully ordered',
          'orderFailure': 'Failed',
          'paymentSuccess': 'Successfully payied',
          'etb': 'ETB',
          'offset': 'Off',
          'theme': 'Themes',
          'home': 'Home',
          'orders': 'Orders',
          'about': 'About us',
          'supports': 'Support',
          'changepassword': 'Change password',
          'newPassword': 'New password',
          'conformPassword': 'Conform password',
          'updatePassword': 'Update password',
          'enterNewPassword': 'Please enter new password',
          'conformationPassword': 'Please enter conformation password',
          'passwordMismach': 'Conformation password mismatch',
          'password': 'Password',
          'logout': 'Logout',
          'categories': 'Categories',
          'products': 'Products',
          'complete': 'Complete',
          'conforms': 'Conform',
          'yes': 'Yes',
          'no': 'No',
          'pending': 'Pending',
          'delivery': 'Delivery ',
          'conformDelivery': 'Conform Delivery',
          'save': 'Save',
          'ok': 'OK',
          'emptyCategory': 'Category is empty',
          'noSuchProduct': 'No such product found',
          'noProduct': 'No product found',
          'emptyCart': 'Cart is empty',
        },
        'am_ET': {
          'login': 'ይግቡ',
          'createAccount': 'መለያ ይፍጠሩ',
          'settings': 'ማስተካከያ',
          'account': 'መለያ',
          'search': 'እቃዎችን ይፈልጉ',
          'price': 'ዋጋ',
          'discount': 'ቅናሽ',
          'descriptions': 'ማብራሪያ',
          'itemsFound': 'ያሉ እቃዎች ',
          'payment': 'ክፍያ',
          'item': 'እቃ',
          'favorites': 'ተወዳጅ',
          'totalPrice': 'ጠቅላላ ዋጋ',
          'total': 'ጠቅላላ',
          'addToCart': 'ወደ ጋሪ ይጨምሩ',
          'buy': 'ይግዙ',
          'pay': 'ይክፈሉ',
          'checkout': 'ጨርሰው ይውጡ',
          'cancel': 'ይሰርዙ',
          'change': 'ይቀይሩ',
          'continue': 'ይቀጥሉ',
          'addToWishList': 'ወደ ምኞት ዝርዝር ይጨምሩ',
          'removeWishList': 'ከምኞት ዝርዝር ያስወግዱ',
          'homePage': 'ዋናዉ ገጽ',
          'cartPage': 'የካርት ገጽ',
          'orderPage': 'ትዕዛዞች ገጽ',
          'cart': 'ጋሪ',
          'setAddress': 'አድራሻ ያስቀምጡ',
          'orderSuccess': 'በተሳካ ሁኔታ አዘዋል',
          'orderFailure': 'አልተሳካም',
          'paymentSuccess': 'በተሳካ ሁኔታ ተከፍሏል',
          'etb': 'ብር',
          'offset': 'ቅናሽ',
          'theme': 'እይታ',
          'home': 'ዋና',
          'orders': 'ትዛዞች',
          'about': 'ስለ እኛ',
          'supports': 'ድጋፍ',
          'changepassword': 'የይለፍ ቃል ይቅይሩ',
          'newPassword': 'አዲስ የይለፍ ቃል',
          'conformPassword': 'የይለፍ ቃል አረጋግጥ',
          'enterNewPassword': 'እባክዎ አዲስ የይለፍ ቃል ያስገቡ',
          'confirmPassword': 'እባክዎ የማረጋገጫ ይለፍ ቃል ያስገቡ',
          'passwordMismach': 'የይለፍ ቃል አለመዛመድ',
          'updatePassword': 'የይለፍ ቃል አዘምን',
          'password': 'የይለፍ ቃል',
          'logout': 'ዘግተው ይዉጡ',
          'categories': 'ምድቦች',
          'products': 'ምርቶች',
          'complete': 'ያጠናቁ',
          'conforms': 'ያረጋግጡ',
          'yes': 'አዎ',
          'no': 'አይ',
          'pending': 'በመጠባበቅ ላይ',
          'delivery': 'መላኪያ ',
          'conformDelivery': 'መድረሱን ያረጋግጡ',
          'save': 'ያስቀምጡ',
          'ok': 'እሺ',
          'emptyCategory': 'ምድብ ባዶ ነው',
          'noSuchProduct': 'እንደዚህ ያለ ምርት አልተገኘም',
          'noProduct': 'ምንም አይነት ምርት አልተገኘም',
          'emptyCart': 'ጋሪ ባዶ ነው',
        },
        'om_ET': {
          'login': 'Seensa',
          'createAccount': 'Akkaawuntii Uumuu',
          'settings': 'Sirreeffama',
          'account': 'Herrega',
          'search': 'Wantoota barbaadi',
          'price': 'Gatiin',
          'discount': 'Gatii gadi bu aa',
          'descriptions': 'Ibsa',
          'itemsFound': 'Wantoota jiran ',
          'payment': 'Kafaltii',
          'item': 'Meeshaa',
          'favorites': 'Jaallatamaa',
          'totalPrice': 'Gatiin waliigalaa',
          'total': 'Ida `ama',
          'addToCart': 'gara gaariitti dabaluu',
          'buy': 'Bitadhaa',
          'pay': 'Kaffaluu',
          'checkout': 'Itti xumuraa',
          'cancel': 'Haquu',
          'change': 'Jijjiirraa',
          'continue': 'Itti fufuu',
          'addToWishList': 'Tarree fedhii irratti dabali',
          'removeWishList': 'Tarree hawwii irraa haqi',
          'homePage': 'Fuula ijoo',
          'cartPage': 'Fuula gaarii',
          'orderPage': 'Fuula ajaja',
          'cart': 'Gaarii',
          'setAddress': 'Teessoo Qusadhu',
          'orderSuccess': 'Milkaa `inaan ajajtaniittu',
          'orderFailure': 'hin milkoofne',
          'paymentSuccess': 'Milkaa`inaan kaffalame',
          'etb': 'qarshii',
          'offset': 'Gatii gadi bu `aa',
          'theme': 'Ilaaluu',
          'home': 'Main',
          'orders': 'Ajaja',
          'about': 'waa`ee keenya',
          'supports': 'Deeggarsa',
          'changepassword': 'Jecha icciitii jijjiiri',
          'newPassword': 'Jecha Darbii Haaraa',
          'conformPassword': 'Jecha Darbii Mirkaneessaa',
          'updatePassword': 'Jecha icciitii haaromsi',
          'enterNewPassword': 'Mee jecha icciitii haaraa galchi',
          'confirmPassword': 'Mee jecha icciitii mirkaneessaa galchaa',
          'passwordMismach': 'jecha icciitii walsimsiisuu dhabuu',
          'password': 'jecha iccitii',
          'logout': 'Cufaatii ba`aa',
          'categories': 'Ramaddiiwwan',
          'products': 'Oomishaalee',
          'complete': 'Guutuu',
          'conforms': 'check in',
          'yes': 'Eeyyee',
          'no': 'Lakki',
          'pending': 'Eeguu',
          'delivery': 'Fe `umsa ',
          'conformDelivery': 'Akka dhufu mirkaneessi',
          'save': 'Qusachuu',
          'ok': 'tole',
          'emptyCategory': 'Ramaddiin duwwaa dha',
          'noSuchProduct': 'Omishni akkasii hin argamne.',
          'noProduct': 'Oomishaaleen hin argamne',
          'emptyCart': 'Gaariin duwwaa dha',
        },
      };
}
